
project_id = "wvkgjhykeflyyntqgyja"

[functions.generate-content]
verify_jwt = false

[functions.meli-callback]
verify_jwt = false

[functions.meli-auth-start]
verify_jwt = false

[functions.meli-refresh]
verify_jwt = false
