// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkgjhykeflyyntqgyja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2dqaHlrZWZseXludHFneWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDgyNzAsImV4cCI6MjA2MzU4NDI3MH0.1hehZ958dsh9FnhNVFZSRgmz6MPVaMKSiMiwjLOR5hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);